spring:
  datasource:
    url: jdbc:mysql://121.4.208.247:3306/spring_security?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: Judge@1024
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      springframework:
        security: trace

# why the port does not work
#  ldap:
#    embedded:
#      ldif: classpath:users.ldif
#      port: 53389
server:
  port: 9000
  servlet:
    context-path: /spring-security-ldap

